### ISSUE TITLE
Same name as commercial software

### ISSUE THREAD

**Issue by r3dey3** [rackerlabs/django-DefectDojo#1]
Just wanted to let you know the name you chosen is the same as a commercial issue tracking software - http://www.seapine.com/testtrack/issue-management

**Comment by cneill** [comment]
Hi r3dey3, thanks for bringing this to our attention. We're doing some brainstorming now to figure out how best to resolve this confusion.

**Comment by devGregA** [comment]
![homer](https://cloud.githubusercontent.com/assets/4741312/6646419/b63abeae-c992-11e4-8010-6ebf9d2ea1a5.gif)

**Comment by devGregA** [comment]
![homer2](https://cloud.githubusercontent.com/assets/4741312/6646439/d4eab66a-c992-11e4-8ad3-f01eef9a6fc4.jpg)

**Comment by rgbkrk** [comment]
You should call it tRacker.

> /me bows out

:bow:

**Comment by grendel513** [comment]
We are in the process of rebranding.  A new name has been chosen and will soon be reflected in all content as well as logos.

**Comment by grendel513** [comment]
The name change and rebranding has been completed.  We encourage everyone to rebase as the v1.0 release has been tagged.
