### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sandeepl337** [rackerlabs/django-DefectDojo#2]
:~/django-TestTrack-master/vagrant_project# vagrant box add precise                                                                                                                                                             32 http://files.vagrantup.com/precise32.box
/root/django-TestTrack-master/Vagrantfile:7:in `<top (required)>': undefined met                                                                                                                                                             hod `configure' for Vagrant:Module (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in `load'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in `block in                                                                                                                                                              procs_for_source'
        from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:41:in `block in capture                                                                                                                                                             _configures'
        from <internal:prelude>:10:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:36:in `capture_configur                                                                                                                                                             es'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:114:in `procs_fo                                                                                                                                                             r_source'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:51:in `block in                                                                                                                                                              set'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in `each'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in `set'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:377:in `block in l                                                                                                                                                             oad_config!'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in `load_confi                                                                                                                                                             g!'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:327:in `load!'
        from /usr/bin/vagrant:40:in `<main>'

**Comment by devGregA** [comment]
I'm also hitting a snag with the vagrant install. We should all note that 1.5 or greater is required.

==> dd: Waiting for machine to boot. This may take a few minutes...
    dd: SSH address: 127.0.0.1:2222
    dd: SSH username: vagrant
    dd: SSH auth method: private key
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
    dd: Warning: Connection timeout. Retrying...
^C==> dd: Waiting for cleanup before exiting...

**Comment by cneill** [comment]
It looks like others ([1](https://github.com/wafflesfm/batter/issues/1), [2](https://github.com/puphpet/puphpet/issues/1)) have had issues like this due to the version of Vagrant installed. If you installed it via rubygems, simply removing that gem and installing the binary for your distro from [vagrantup.com](https://www.vagrantup.com/downloads.html) should do the trick.

Let us know if this doesn't fix your issue.

**Comment by cneill** [comment]
Gonna go ahead and close this. If you continue to have installation issues, open up a new issue and let us know.
