### ISSUE TITLE
Table 'django_site' doesnt exist

### ISSUE THREAD

**Issue by parthibann** [rackerlabs/django-DefectDojo#27]
1. I've installed this app in 'linuxmint' OS and tried to run it using the command "python manage.py runserver" and the app started without any issues.
![1](https://cloud.githubusercontent.com/assets/4667360/6892109/93c1a56e-d6de-11e4-9862-6d0f511d7af4.png)
2. but when i tried to view the site in browser (http://127.0.0.1:8000) im getting 500 internal server error.
![3](https://cloud.githubusercontent.com/assets/4667360/6892150/f6a67218-d6de-11e4-98a2-40d2029b2df4.png)
3. and then i checked the database by manually logging in, the specifed table(django_site) does not exist in the db also.

**Comment by grendel513** [comment]
Hi - 

Thanks for the feedback.  Can you please provide us with more information?

1.  Did you use the `setup.bash` script to install your copy?
1.  If you did not, did your run `./manage makemigrations` and `./manage.py migrate`?

These two commands are necessary to create all the database tables the system needs, without them the tables are not created.  `setup.bash` script will run these commands for you.

Thanks,

@grendel513

**Comment by parthibann** [comment]
thanks @grendel513 "python manage.py migrate" worked for me, now im getting the login page but dono the username and password. where can i create and manage users? is there an signup page?

**Comment by grendel513** [comment]
@parthibann - DefectDojo takes advantage of Django Users.  The best thing for you to do is run `python manage.py createsuperuser` and follow the prompts.  That will give you a user that has admin rights on the system.  The `setup.bash` runs this for you as well.

**Comment by p0g00g0p** [comment]
I encountered the same error
I tried to install on debian 9 without success.
