### ISSUE TITLE
More screenshorts and demo is required

### ISSUE THREAD

**Issue by parthibann** [rackerlabs/django-DefectDojo#3]
* Could be better if this app is hosted in https://www.pythonanywhere.com/ or https://www.heroku.com/ or using some other PAAS providers free account and then linked it in markdown.md file

**Comment by sandeepl337** [comment]
+1

**Comment by grendel513** [comment]
Thanks for reaching out, we are in the works of deploying a demo site and adding more documentation and screenshots.  We will update this issue and the README.md when that is done.

**Comment by cneill** [comment]
I've just added a [getting started guide](https://github.com/rackerlabs/django-DefectDojo/blob/master/doc/getting_started.md) with screenshots, and we will be looking into deploying a demo version of the application in the near future.

**Comment by devGregA** [comment]
@cneill nice! Do we add something to the readme file for a quick reference?

**Comment by devGregA** [comment]
doh! It's already there, do we want to close this or do we want to get the demo up first? Thoughts @grendel513 ?

**Comment by grendel513** [comment]
I'm game either way...the demo site wont be ready until we automate the "reset" every so often...

**Comment by devGregA** [comment]
Ah gotcha. Anything I can do to help with that? I can take on that automation.

**Comment by sandeepl337** [comment]
Great information :)

**Comment by cneill** [comment]
We have created a demo site for you to check out DefectDojo without installing it [here](http://defectdojo.pythonanywhere.com/).

To log in as an administrator, you can log in with the username "admin" and the password "administrator". If you want to see what it looks like from a Product owner's perspective, you can log in with username "product_owner" and password "product_owner".

Let us know what you think!
