### ISSUE TITLE
Integration with LDAP for authentication?

### ISSUE THREAD

**Issue by HexHash64** [rackerlabs/django-DefectDojo#38]
For my use case, I prefer to integrate this with LDAP and not rely on django's authentication system. 

Is it possible to configure DefectDojo to authenticate against an internal LDAP Directory Server (eg OpenLDAP or Active Directory) ? I've looked at [django-auth-ldap](https://pythonhosted.org/django-auth-ldap/), but I'm new to Django and don't understand how to integrate this with DefectDojo...if it's possible at all.

**Comment by grendel513** [comment]
@HexHash64 - [django-auth-ldap](https://pythonhosted.org/django-auth-ldap/) is the perfect way to implement LDAP auth for DefectDojo.  We leverage Django for most everything, an authentication backend is no exception.

If you follow the instructions for django-auth-ldap it will work in DefectDojo as well.  

Extending DefectDojo is easy, you can either find other django projects that fit your need or write your own like we have - see [defectDojo-engagement-survey](https://github.com/grendel513/defectDojo-engagement-survey) for an example of how to extend DefectDojo with your own Django apps.

Hope this helps!
