### ISSUE TITLE
Change license from CC to ?

### ISSUE THREAD

**Issue by cneill** [rackerlabs/django-DefectDojo#40]
Since Creative Commons suggests [not using their license for software](https://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F), we need to find another, compatible license.

Potential candidates:
- BSD
- Apache
- GPL

**Comment by MicksMix** [comment]
I'd strongly prefer BSD, with a close second choice of the Apache license. I'm currently evaluating DefectDojo for use in my organization, and if it were GPL licensed it would be off limits for legal reasons. I think other medium to large organizations would have similar restrictions to mine if it were GPL licensed.

IMHO, go with the least restrictive open-source license and go with BSD.

**Comment by HexHash64** [comment]
I'd strongly prefer BSD, with a close second choice of the Apache license. I'm currently evaluating DefectDojo for use in my organization, and if it were GPL licensed it would be off limits for legal reasons. I think other medium to large organizations would have similar restrictions to mine if it were GPL licensed.

IMHO, go with the least restrictive open-source license and go with BSD.

**Comment by cneill** [comment]
Thanks for the feedback! BSD is definitely my preferred option as well. We'll provide an update next week once we've made a final decision.
