### ISSUE TITLE
Request for Additional Functionality: Removing Remediated Items from Scan Uploads

### ISSUE THREAD

**Issue by cgalligan** [rackerlabs/django-DefectDojo#44]
It would be great if as new Nessus scans are run and uploaded as part of an Engagement, they could be compared against existing results and items that have been remediated no longer appear in results and are marked as mitigated along with the date.

**Comment by grendel513** [comment]
Latest commit 5794b09 takes care of this feature request.  All upload imports are now re-uploadable.
