### ISSUE TITLE
Can't Remove Endpoints

### ISSUE THREAD

**Issue by devGregA** [rackerlabs/django-DefectDojo#46]
Hi Jay,

During Triage I tried to update some findings, but was unable to delete endpoints.

**Comment by grendel513** [comment]
Do you mean remove endpoints from the Finding or completely delete Endpoints from the database?

**Comment by grendel513** [comment]
After discussing it, we can make the interaction with the add related form better.  Will work on this as an enhancement since there is no actual bug, just awkward interaction.

**Comment by grendel513** [comment]
new interaction now available
