### ISSUE TITLE
500 on Scan Upload

### ISSUE THREAD

**Issue by mattvaldes** [rackerlabs/django-DefectDojo#54]
Uploading a Nessus scan CSV results in a 500 error. The test is created, but the scan findings are not populated within the test.

Steps to recreate
1. Add product
2. Add engagement
3. From the Tests section of the engagement, select "Import Scan Results" from the drop-down menu
4. Complete scan upload information
4a. Enter "Scan Completion Date"
4b. Select "Minimum Severity" 
4c. Select "Nessus Scan" as the Scan type
4d. Browse to the Nessus scan results CSV file
4e. Click "Upload File"
5. Note "Server Error (500)" from /engagement/###/import_scan_results
5a. Note creation of new "Nessus Scan" test within the engagement.

**Comment by mattvaldes** [comment]
Uploading a .nessus file seems to work properly.

**Comment by grendel513** [comment]
Thanks for both the issue report and the added info about the .nessus report.  I have fixed the CSV upload with commit 6b09fe8
