### ISSUE TITLE
Application Metadata

### ISSUE THREAD

**Issue by aaronweaver** [rackerlabs/django-DefectDojo#59]
Create additional meta data for an application. For example:

App: # of users, revenue, Business Criticality, Lifecycle (Where in the dev lifecycle), Origin (internally developed, COTS, internal, Technologies (What is the app environment, hardware, OS etc.)
Regulations: PCI, HIPPA, SoX etc.

**Comment by devGregA** [comment]
I wonder if this would tie together well with tags?

**Comment by devGregA** [comment]
hey @grendel513 @cneill I'm going to take this one on. Just FYI so we don't duplicate efforts.

**Comment by cneill** [comment]
Sounds good @devGregA. At the risk of JIRAfication, should we allow custom fields, or just have a standard set?

**Comment by devGregA** [comment]
I'm going to start w/  tagging like linkedin does for skills @cneill at the application level

**Comment by grendel513** [comment]
@devGregA there are a number of Django tagging apps out there already...no need to reinvent the wheel if one matches our needs.  Here are a few I looked into when investigating #61:
- https://github.com/Fantomas42/django-tagging
- https://github.com/alex/django-taggit
- https://github.com/svetlyak40wt/django-tagging-ng

If using these then it could take care of #61 and #59 with minimal effort.

**Comment by grendel513** [comment]
@devGregA Additionally, the UI component could be implemented with http://getbootstrap.com/components/#labels

**Comment by grendel513** [comment]
@devGregA - hey Greg, where are we on this one...have you started coding on it?  If not, would you mind if I took it over?

**Comment by devGregA** [comment]
Hey @grendel513. Feel free to nab it. Right now I'm working on intake and de-duplication.

**Comment by grendel513** [comment]
@devGregA - cool, i'll get it then.

**Comment by grendel513** [comment]
@devGregA @cneill - I am going to take two approaches.  Will implement tagging at the Product, Engagement, Endpoint, Finding and Test models.  Additionally, I will add the possibility to include name/value pair descriptor to Product.

**Comment by devGregA** [comment]
@grendel513 Sounds like this would also solve the person table @aaronweaver was talking about in the other issue.
