### ISSUE TITLE
Organization/Line of Business

### ISSUE THREAD

**Issue by aaronweaver** [rackerlabs/django-DefectDojo#60]
I'd like the ability to define multiple organizations and optionally lines of business associated with each organization.

**Comment by devGregA** [comment]
I remember Matt T brought this up when we were discussing needs for Dojo to work for Pearson. Would 'product types' (under the product tab) work for this?

**Comment by devGregA** [comment]
Hi @aaronweaver I've been going back through the enhancements to prioritize / reevaluate. Will the 'Product Type' field work for your use case?

**Comment by aaronweaver** [comment]
Hi @devGregA, that's how I'm using it now. If we had tagging that would probably close this out.

**Comment by devGregA** [comment]
Hi @aaronweaver sounds good. Tagging is definitely high on the priority list after I finish the intake work. I'm going to close this one since we already have tagging as another issue.
