### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by aaronweaver** [rackerlabs/django-DefectDojo#61]
The ability to create arbitrary tags and assign those tags to an application.

**Comment by grendel513** [comment]
@aaronweaver, @devGregA, @cneill - #59 and #61 have been completed and committed to master.  You will need to add 'tagging' and 'custom_field' to INSTALLED_APPS in your settings.py.  Additionally ./manage makemigrations and ./manage.py migrate will have to be run.

**Comment by grendel513** [comment]
<img width="1439" alt="screen shot 2016-08-01 at 4 11 30 pm" src="https://cloud.githubusercontent.com/assets/233694/17309190/3f7483f8-5803-11e6-9b0a-f1ee5082eae7.png">

**Comment by devGregA** [comment]
Wow!!! https://media.giphy.com/media/7rj2ZgttvgomY/giphy.gif

**Comment by aaronweaver** [comment]
@grendel513 That's fantastic! Thanks!
