### ISSUE TITLE
NGINX config proxy_pass vs upstream

### ISSUE THREAD

**Issue by 4lGxqmy9kzDsq6PlGSVH** [rackerlabs/django-DefectDojo#67]
Hi,

I deployed DD behing an reverse proxy, everything is fine except for browsing API Docs who are trying to load URLs along these lines. http://localhost:8000/api/v1/doc/schema/engagements?_...

Additionally, this also causes mixed content warnings in case of an HTTPS deployment.
For info, references to hosts are handled properly in dojo/templates/dojo/api_key.html on line 18

**Comment by devGregA** [comment]
Thanks @4lGxqmy9kzDsq6PlGSVH,  I'll take a look.

**Comment by devGregA** [comment]
@4lGxqmy9kzDsq6PlGSVH, I looked at a copy that was fronted with NGINX and didn't have the same issue. Could you give me more info on your stack? Is your proxy on the same server, are they separate instances, etc? @grendel513 any thoughts on this?

**Comment by grendel513** [comment]
hi @4lGxqmy9kzDsq6PlGSVH, @devGregA - 

We don't hardcore a reference to any host in the JavaScript associated with DefectDojo.  That piece of code comes directly from the django-tastypie-swagger project.  You can see where and how ti is used and generated here: https://github.com/concentricsky/django-tastypie-swagger/search?utf8=%E2%9C%93&q=discovery_url

In my installation the discovery_url becomes:

    url: "/api/v1/doc/resources/",

Which as you can see does not have a host so the routing should be handled by your web server (Ngnix, Apache, etc) configuration.

Here is a search of the entire DefectDojo code base showing that the only references to locahost are in database connection settings, form help texts and a couple of regex used in upload parsers: https://github.com/rackerlabs/django-DefectDojo/search?utf8=%E2%9C%93&q=localhost

The source of our demo site also helps confirm there is no hardcoded localhost value: https://defectdojo.pythonanywhere.com/api/v1/doc/

Let us know how we can help you triage your particular installation.

**Comment by 4lGxqmy9kzDsq6PlGSVH** [comment]
Hi, Thanks for your help here!

Here's the *very basic* nginx config I use. Know what I am doing wrong? 
`
server {
        listen 443;
        server_name localhost;

        access_log  /var/log/nginx/reverse-proxy.access.log  combined;
        error_log  /var/log/nginx/reverse-proxy.error.log;

        ssl on;
        ssl_certificate cert.crt;
        ssl_certificate_key cert.key;

        ssl_session_timeout 30m;

        ssl_protocols TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;

        ## send request back to localhost 8000 ##
        location / {
                proxy_pass http://localhost:8000/;
        }
}
`

Thanks in advance!

**Comment by devGregA** [comment]
Ah, @4lGxqmy9kzDsq6PlGSVH try upstream instead of proxy_pass:
'upstream defectdojo {
  server 127.0.0.1:8000;
}'
This should be outside of server, e.g.:
'upstream defectdojo {
  server 127.0.0.1:8000;
}
server{
...
}
'
Please let me know if it fixes / doesn't fix the proxy.
@grendel513, I can definitely see others running into this. If you're okay with it, I'll come up with an NGINX template we can include? I'll kick it to you privately for review before the PR?

**Comment by devGregA** [comment]
Keep this open for tracking, to hopefully resolve.

**Comment by devGregA** [comment]
Closing, because we haven't heard back.
