### ISSUE TITLE
defusedxml is a more secure alternative to xml.etree

### ISSUE THREAD

**Issue by MicksMix** [rackerlabs/django-DefectDojo#68]
xml.etree is vulnerable (according to defusedxml documentation) the [following XML attacks](https://pypi.python.org/pypi/defusedxml#python-xml-libraries):

 - [billion Laughs](https://pypi.python.org/pypi/defusedxml#billion-laughs-exponential-entity-expansion)
 - [quadratic blowup](https://pypi.python.org/pypi/defusedxml#quadratic-blowup-entity-expansion)
 - [XML Inclusion](https://pypi.python.org/pypi/defusedxml#xinclude) (a feature that can present security holes)

Fortunately, the Python community has [responded with defusedxml](https://docs.python.org/2/library/xml.html#defused-packages). It is a near drop-in replacement for xml.etree.

I found xml.etree used in `parser.py` under each subfolder here:
[dojo/tools](https://github.com/rackerlabs/django-DefectDojo/tree/master/dojo/tools)

You should replace `xml.etree` with `defusedxml`.

**Comment by devGregA** [comment]
Thanks @MicksMix I'll take a look shortly.

**Comment by devGregA** [comment]
@grendel513 @cneill I agree with @MicksMix finding, xml.etree seems to be reported as vulnerable to XEE. I'll submit a PR shortly

**Comment by devGregA** [comment]
@cneill PR submitted. Would you review? grendel is on vacation.

**Comment by grendel513** [comment]
#70 fixes this
