### ISSUE TITLE
Installation error with auditlog

### ISSUE THREAD

**Issue by devGregA** [rackerlabs/django-DefectDojo#74]
Hey guys, I'm hitting an install error not related to the missing overextends dependency. Something is wrong with auditlog.

Below is the relevant dump information, I'm using python 2.7.10, Django 1.8.4, Ubuntu 15.10

Operations to perform:
  Synchronize unmigrated apps: gunicorn, staticfiles, messages, humanize, polymorphic, tastypie_swagger, overextends, djangobower
  Apply all migrations: dojo, watson, sessions, admin, sites, auth, tastypie, contenttypes, auditlog
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying auditlog.0004_logentry_detailed_object_repr...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
.....

django.db.utils.OperationalError: (1101, "BLOB/TEXT column 'additional_data' can't have a default value")
/usr/local/lib/python2.7/dist-packages/auditlog/models.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

**Comment by devGregA** [comment]
@grendel513, sorry this is blocking my defusedXML tinkering to make sure everything is working correctly.

**Comment by grendel513** [comment]
#70 fixes this as well...auditlog is not at the latest version
