### ISSUE TITLE
Demo site - Exceptiion while viewing potential finding

### ISSUE THREAD

**Issue by mtesauro** [rackerlabs/django-DefectDojo#77]
If you log into the demo site as an admin, add an engagement, add a potential finding then click on the link for the new potential finding, you get the following exception:

```
Page not found (404)
Request Method: 	GET
Request URL: 	https://defectdojo.pythonanywhere.com/finding/1
Raised by: 	dojo.finding.views.view_finding

No Finding matches the given query.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

**Comment by grendel513** [comment]
@mtesauro did you use a bookmark to navigate to the finding, or did you click from a listing.  I tested the finding details page at https://defectdojo.pythonanywhere.com/finding/115 and it works.  If the ID does not exist, like yours (1) you will get a 404, which is appropriate.

**Comment by grendel513** [comment]
@mtesauro This should be all good on the next daily rebuild of python anywhere demo site which should be tonight.  Thanks for the heads up!
