### ISSUE TITLE
The PythonAnywhere Demo is broken.

### ISSUE THREAD

**Issue by devGregA** [rackerlabs/django-DefectDojo#81]

**Comment by grendel513** [comment]
Because of this...https://blog.pythonanywhere.com/128/

I'll get it up and running again.

**Comment by grendel513** [comment]
@devGregA It is up and running again.  I also updated the code to the latest from master.  Additionally, I updated the code in refresh.bash to reflect the new mysql host name.

**Comment by devGregA** [comment]
@grendel513 Thanks! You're awesome.
