### ISSUE TITLE
default interface/port

### ISSUE THREAD

**Issue by morxploit** [rackerlabs/django-DefectDojo#83]
The applications listens by default on 127.0.0.1. Is there a way to change it to 0.0.0.0? I have the app installed on a remote VPS and i would like to be able to access through the internet.

Thanks a lot and sorry if this has been already referenced.

**Comment by devGregA** [comment]
Hi @morxploit , thanks for trying Dojo out! For production use, I would suggest proxying Dojo through Nginx or better yet Nginx + Gunicorn. If you're still just exploring / playing with Dojo and aren't transmitting sensitive data, you can run Dojo on all interfaces using the developer server by executing:
`python manage.py runserver 0.0.0.0:80`

**Comment by morxploit** [comment]
Awesome, thanks for the quick answer @devGregA
