### ISSUE TITLE
500 on Nessus uploads - 'Finding' object has no attribute 'unsaved_req_resp'

### ISSUE THREAD

**Issue by MKgridSec** [rackerlabs/django-DefectDojo#85]
Hello,
Seeing a 500 error the first time I try to import a nessus scan result. 
same error using .csv or .nessus format. When I click back, a single finding is available. If use the re-import option it seems to import successfully.
 
Running Centos 7.2 setup via the setup.bash scripts and pip installed from epel-release

Environment:

Request Method: POST
Request URL: http://192.168.128.75:8000/engagement/2/import_scan_results

Django Version: 1.8.10
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'polymorphic',
 'overextends',
 'django.contrib.admin',
 'django.contrib.humanize',
 'gunicorn',
 'tastypie',
 'djangobower',
 'auditlog',
 'dojo',
 'tastypie_swagger',
 'watson')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'dojo.middleware.LoginRequiredMiddleware')

Traceback:
File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/root/django-DefectDojo/dojo/engagement/views.py" in import_scan_results
  260.                     if len(item.unsaved_req_resp) > 0:

Exception Type: AttributeError at /engagement/2/import_scan_results
Exception Value: 'Finding' object has no attribute 'unsaved_req_resp'

**Comment by devGregA** [comment]
Hi @MKgridSec sorry to hear you're having this issue. Off the top of my head it sounds like a syncdb issue. Running: `python manage.py syncdb` . May fix the issue. Let me fire up a CentOS VM and see if I can reproduce. I'll get back to you shortly.

**Comment by grendel513** [comment]
@devGregA, @MKgridSec - the issue is that in the view I did not check to make sure the Finding item has the attribute unsaved_req_resp before utilizing it.  It is not an attribute defined in the Model, but one assigned to it later in the upload process.  Database sync will not resolve the issue.  I will commit code here shortly to address it.

**Comment by grendel513** [comment]
@MKgridSec (cc: @devGregA) - Code committed, please update and let us know if it resolves your issue.

**Comment by devGregA** [comment]
Awesome! Thanks @grendel513

**Comment by MKgridSec** [comment]
@devGregA @grendel513 Thank you! I've re-tested and confirmed that uploads are now working

**Comment by devGregA** [comment]
Awesome! Thanks @MKgridSec
