### ISSUE TITLE
Missing upload / mandatory field

### ISSUE THREAD

**Issue by davevs** [rackerlabs/django-DefectDojo#94]
When I try to create a new finding or edit a finding from a ZAP report, there's a mandatory field 'Image'. However I can't find a way to upload anything.

**Comment by devGregA** [comment]
Hi @davevs sorry about that! My PR that just got merged should fix it. Please let me know if you continue to have issues.

**Comment by grendel513** [comment]
@davevs - @devGregA is correct, if you pull from master and run ./manage.py makemigrations and ./manage.py migrate the issue should be resolved.  Please let us know if this fixes it for you so we can close issue.  Thanks!

**Comment by grendel513** [comment]
@devGregA, @davevs See commit d1e2495 - I removed null=False which has no effect on ManyToMany fields.  Left blank=True and removed images from all Finding forms as they have their own update/store/delete workflow. `./manage.py makemigrations` and `./manage.py migrate` are needed.

**Comment by davevs** [comment]
Issue is fixed.
