### ISSUE TITLE
Error when adding engagement

### ISSUE THREAD

**Issue by davevs** [rackerlabs/django-DefectDojo#96]
If I add a new engagement and save it I get the following error:

UnboundLocalError at /engagement/3

local variable 'fpage' referenced before assignment

Request Method: 	GET
Request URL: 	http://localhost:8000/engagement/1
Django Version: 	1.8.10
Exception Type: 	UnboundLocalError
Exception Value: 	

local variable 'fpage' referenced before assignment

Exception Location: 	/home/xebia/django-DefectDojo-master/dojo/engagement/views.py in view_engagement, line 199
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/xebia/django-DefectDojo-master',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',
 '/home/xebia/django-DefectDojo-master']

**Comment by devGregA** [comment]
Thanks @davevs. I think I see the problem. https://github.com/rackerlabs/django-DefectDojo/blob/master/dojo/engagement/views.py#L195 @grendel513 this may require additional changes to view_risk in dojo/engagements/views.py. I'm not sure what fpage is, but it looks like if an engagement doesn't have findings it is passed to templates w/out being assigned a value. I'll push a hot fix to address this at least for engagements. On the bright side the CI we're working on incorporating should catch things like this in the future :D

**Comment by devGregA** [comment]
hi @davevs thanks again for hanging in there. We try really hard to keep Dojo stable, but the two major features we pushed introduced some issues. I'm working on getting CI testing up to reduce these types of things. I've pushed an update that should resolve the issue. I will test the fix shortly, and review your PR.

**Comment by davevs** [comment]
@devGregA No problem, I understand. More than happy to help :)

**Comment by grendel513** [comment]
@devGregA - my bad i can have this fixed ASAP is you have not started

**Comment by grendel513** [comment]
@davevs @devGregA - should be fixed, i tested it with my install.  Pull from either master or develop to get fix.  Sorry for the inconvenience.

**Comment by davevs** [comment]
@grendel513 No problem, thanks for the quick fix again.
